#!/usr/bin/env python
"""
Step 8: Publication figure generation.

Assembles all panels into composite publication figures.
All figures are regenerable from saved intermediate results.

Run: python scripts/07_figures.py
"""

import logging
import sys
from pathlib import Path

sys.path.insert(0, "src")

import matplotlib.gridspec as gridspec
import matplotlib.pyplot as plt
import scanpy as sc

from sctda_plasticity.config import (
    DATA_PROCESSED,
    FIGURES_DIR,
    TIMEPOINT_COLORS,
)
from sctda_plasticity.visualize import save_figure, set_publication_style

logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s: %(message)s")
logger = logging.getLogger(__name__)

MANUSCRIPT_DIR = Path("manuscript/figures")


def fig1_study_overview():
    """Fig 1: Study design + standard analysis overview."""
    logger.info("Generating Fig 1: Study overview")

    h5ad_path = DATA_PROCESSED / "pc9_erlotinib_analyzed.h5ad"
    if not h5ad_path.exists():
        logger.warning("Analyzed data not found, skipping Fig 1")
        return

    adata = sc.read_h5ad(h5ad_path)
    set_publication_style()

    fig = plt.figure(figsize=(180 / 25.4, 140 / 25.4))
    gs = gridspec.GridSpec(2, 3, figure=fig, hspace=0.4, wspace=0.35)

    # Panel A: UMAP colored by timepoint
    ax = fig.add_subplot(gs[0, 0])
    if "timepoint" in adata.obs.columns:
        for tp in sorted(adata.obs["timepoint"].unique()):
            mask = adata.obs["timepoint"] == tp
            ax.scatter(
                adata.obsm["X_umap"][mask, 0], adata.obsm["X_umap"][mask, 1],
                c=TIMEPOINT_COLORS.get(tp, "#666"), label=tp, s=3, alpha=0.6,
            )
        ax.legend(fontsize=5, markerscale=3, frameon=False)
    ax.set_xlabel("UMAP1")
    ax.set_ylabel("UMAP2")
    ax.set_title("a", loc="left", fontweight="bold")

    # Panel B: UMAP colored by cluster
    ax = fig.add_subplot(gs[0, 1])
    if "leiden" in adata.obs.columns:
        sc.pl.umap(adata, color="leiden", ax=ax, show=False, title="", legend_loc="right margin",
                    size=3, frameon=False)
    ax.set_title("b", loc="left", fontweight="bold")

    # Panel C: UMAP colored by EMT score
    ax = fig.add_subplot(gs[0, 2])
    if "emt_score" in adata.obs.columns:
        sc.pl.umap(adata, color="emt_score", ax=ax, show=False, title="EMT score",
                    size=3, frameon=False, color_map="RdBu_r")
    ax.set_title("c", loc="left", fontweight="bold")

    # Panel D: Cell cycle phase
    ax = fig.add_subplot(gs[1, 0])
    if "phase" in adata.obs.columns:
        sc.pl.umap(adata, color="phase", ax=ax, show=False, title="", size=3, frameon=False)
    ax.set_title("d", loc="left", fontweight="bold")

    # Panel E: Diffusion pseudotime
    ax = fig.add_subplot(gs[1, 1])
    if "dpt_pseudotime" in adata.obs.columns:
        sc.pl.umap(adata, color="dpt_pseudotime", ax=ax, show=False, title="Pseudotime",
                    size=3, frameon=False, color_map="viridis")
    ax.set_title("e", loc="left", fontweight="bold")

    # Panel F: PAGA
    ax = fig.add_subplot(gs[1, 2])
    if "paga" in adata.uns:
        sc.pl.paga(adata, ax=ax, show=False, title="", frameon=False)
    ax.set_title("f", loc="left", fontweight="bold")

    save_figure(fig, "fig1_study_overview", str(MANUSCRIPT_DIR))
    save_figure(fig, "fig1_study_overview")
    plt.close(fig)


def fig2_persistence():
    """Fig 2: Persistence barcodes and diagrams across timepoints."""
    logger.info("Generating Fig 2: Topological analysis")
    # Individual panels already generated by 03_topology.py
    # Here we just verify they exist
    expected = [
        "fig2_a_persistence_barcodes",
        "fig2_b_h1_persistence_diagrams",
        "fig2_d_wasserstein_heatmap",
    ]
    for name in expected:
        for fmt in ["pdf", "png"]:
            path = FIGURES_DIR / f"{name}.{fmt}"
            if path.exists():
                # Copy to manuscript dir
                import shutil
                dest = MANUSCRIPT_DIR / f"{name}.{fmt}"
                shutil.copy2(path, dest)
                logger.info(f"  Copied {path.name} → manuscript/")


def fig4_ablation():
    """Fig 4: Cell cycle ablation."""
    logger.info("Generating Fig 4: Cell cycle ablation")
    expected = ["fig4_a_barcodes_with_cc", "fig4_b_barcodes_without_cc"]
    for name in expected:
        for fmt in ["pdf", "png"]:
            path = FIGURES_DIR / f"{name}.{fmt}"
            if path.exists():
                import shutil
                dest = MANUSCRIPT_DIR / f"{name}.{fmt}"
                shutil.copy2(path, dest)
                logger.info(f"  Copied {path.name} → manuscript/")


def main():
    logger.info("=== Figure Generation ===")
    MANUSCRIPT_DIR.mkdir(parents=True, exist_ok=True)
    FIGURES_DIR.mkdir(parents=True, exist_ok=True)

    fig1_study_overview()
    fig2_persistence()
    fig4_ablation()

    logger.info(f"\n=== Figures saved to {MANUSCRIPT_DIR} and {FIGURES_DIR} ===")


if __name__ == "__main__":
    main()
